project:
  output-dir: docs
  type: website
  render:
    - "**/*.qmd"
    - "!files/**"
    - "!ae/files/**"
  resources:
    - data/
    - files/
    - ae/files/

website:
  page-navigation: true
  title: "POL 051 - Summer 2026"
  description: "Homepage for POL 051 - The Scientific Study of Politics at UC Davis, Summer 2026."
  site-url: "http://haleydaarstad.com/pol051-su26/"

  repo-url: http://haleydaarstad.com/pol051-su26/
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Haley Daarstad"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: clipboard-check
        href: https://login.canvas.ucdavis.edu/
        text: "Canvas"
      - icon: code-square
        href: https://posit.cloud
        text: "Posit Cloud"
      - icon: book
        text: "Course books"
        menu:
          - text: R for Data Sceince
            url: https://r4ds.hadley.nz/
          - text: ModernDive
            url: https://moderndive.com/v2/index.html
          - text: The Mixtape
            url: https://mixtape.scunning.com/

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: index.qmd
            text: Schedule
          - href: course-faq.qmd
            text: FAQ
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Data Options
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week-3.qmd
            text: "Week 3"
          - href: weeks/week-4.qmd
            text: "Week 4"
          - href: weeks/week-5.qmd
            text: "Week 5"
          - href: weeks/week-6.qmd
            text: "Week 6"
      - section: "Code Examples"
        contents:
          - href: supplemental/r-basics.qmd
            text: R Basics
          - href: supplemental/data-vis.qmd
            text: Data Visualization (ggplot2)
          - href: supplemental/data-wrangling.qmd
            text: Data Wrangling (ggplot2)
          - href: supplemental/models.qmd
            text: Linear Regression Models
          - href: supplemental/hypothesis-tests.qmd
            text: t-tests and Correlations
          - href: supplemental/data-gen.qmd
            text: Random Data Generation

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual