---
title: "Syllabus"
---

## Course info

|   | Day | Time | Location |
|------------------|------------------|------------------|------------------|
| Lectures | Mon, Tue & Wed. | 12:10 pm - 1:50 pm | Hoagland Hall 168 |
| Discussion/Lab | Thu | 12:10 pm - 1:50 pm | Teaching and Learning Complex 2212 |
| Office Hours | Tue | 2:00 - 4:00 PM | Kerr Hall 569 |

## Learning objectives

By the end of this course you will be able to...

-   Analyze real-world data to answer questions about different relationships.
-   Feel comfortable manipulating data in R
-   Craft effective visualizations of patterns in data
-   Draw causal diagrams and identify obstacles to causal claims
-   Understand the basics of regression and uncertainty

## Community and UC Davis Policies

### Inclusive community

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength, and benefit. It is my intent to present materials and activities that are respectful of diversity. Your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

Furthermore, I would like to create a learning environment for my students that supports a diversity of thoughts, perspectives and experiences, and honors your identities. To help accomplish this:

-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. If you prefer to speak with someone outside of the course, your academic dean is an excellent resource.
-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please let me or a member of the teaching team know.

This is a political science course, and as such we will be discussing political issues. As each of us comes into the section with unique opinions about political issues, there may be disagreements. I insist we discuss our differences with respect, civility, and empathy. Please do your best to keep an open mind about your peers’ perspectives as your peers will expect the same of you.

*Note*: This does not mean you should avoid participating if/when you have an alternative point of view just because you may not wish to provoke an argument. Be bold, and share what you think (respectfully)

-   *If I believe any of the discussion is becoming disrespectful or includes hateful or inappropriate speech, I hold the right to end the discussion.*

### Accessibility

If there is any portion of the course that is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.

It is the Professor’s responsibility to help make this course accessible to all students. If you believe you have a disability requiring an accommodation or would like additional information about the resources available for students with disabilities, please visit the UC Davis Student Disability Center website at [sdc.ucdavis.edu](sdc.ucdavis.edu).

-   Students must contact me about any accommodations in advance.

-   Outside Resources - The Student Academic Success Center is a campus wide resource assisting students by helping them improve in study skills, academic writing, and other specific topics

### Mandatory Reporter

In my role as faculty, **I am required by policy to report concerns that come to my attention related to sexual harassment, sexual violence, discrimination, or harassment involving students.**  Please know you are still free to discuss these concerns with me, but I will need to pass along any information shared with me to the Harassment and Discrimination Assistance and Prevention Program (HDAPP) so they can reach out to you and talk to you about resources and possible resolution options.  If you would prefer to speak to a confidential resource, who does not have the same responsibility to report, I can help you get connected. 

Alternatively, here is a link to information about available resources on campus (including confidential resources):  <https://hdapp.ucdavis.edu/resources>.  Also, here is a link to information about reporting directly to HDAPP:  <https://hdapp.sf.ucdavis.edu/report-incident>.

### **Counseling & Psychiatry Services**

Life at Davis can be complicated and challenging. You might feel overwhelmed, experience anxiety or depression, or struggle with relationships or family responsibilities. [UC Davis Counseling Services](https://shcs.ucdavis.edu/services/counseling-services) provide *confidential* support for students who are struggling with mental health and emotional challenges. Please do not hesitate to contact them for assistance—getting help is a smart and good thing to do.

## Communication

-   What are office hours for?
    -   Office hours are when the the professor sets aside two hours each week making themselves available to students. Office hours are often underutilized by all students in college. Consider this your time.
    -   You do not need an appointment to come by.
    -   My job as a Professor is to help each of you succeed, however, I can only help you if you ask. (PLEASE COME ASK ME!)
    -   I strongly encourage students to come to my office hours and chat about topics from the readings or lectures, talk over potential study strategies, or to simply converse.
-   What are Emails for?
    -   If your question cannot wait until office hours, section, or class, then students should/may use email to contact their Professor. However, please note, email should not be used as an alternative to direct conversation or an in-depth discussion.
    -   As a simple rule of thumb, emails should be used to address quick questions, not for requests to exhaustively review material from lecture or section.
    -   I will respond to emails within one business day, so between 9 am and 6 pm on weekdays. This means if you email me passed 6 pm on a weekday you will not receive any email till the next day in the morning around 9 am. If you email me on the weekends or passed Friday at 6 pm, I will respond promptly on Monday
    -   I will not respond to emails that are rude, unintelligible, or inquiring about information readily accessible on the syllabus.
-   I will typically communicate announcements about section through Canvas. Please make sure your Canvas information is up to date and that you check it frequently over the quarter.

## Course Materials

All materials for this course are **free and online.** You will do all of your analysis with the open source (and free) programming language R and RStudio.

[Cunningham, S. (2021). *Causal inference: The mixtape*. Yale university press.](https://mixtape.scunning.com/)

[Wickham, H, Çetinkaya-Rundel,, M & Grolemund, G. *R for Data Science*(2e). O'Reilly.](https://r4ds.hadley.nz/)

["**Statistical Inference via Data Science**: A ModernDive into R and the Tidyverse\
(Second Edition)" was written by Chester Ismay, Albert Y. Kim, and Arturo Valdivia\
Foreword by Kelly S. McConville. It was last built on May 24, 2026.](https://moderndive.com/v2/index.html)

## Lectures and labs

The goal of both the lectures and the labs is for them to be as interactive as possible. My role as instructor is to introduce you new tools and techniques, but it is up to you to take them and make use of them. A lot of what you do in this course will involve writing code, and coding is a skill that is best learned by doing. Therefore, as much as possible, you will be working on a variety of tasks and activities throughout each lecture and lab. You are expected to attend all lecture and lab sessions and meaningfully contribute to in-class exercises and discussion. Additionally, some lectures will feature [application exercises] that will be graded, this will be counted as your attendance for participation.

You are expected to bring a laptop to each class so that you can take part in the in-class exercises. Please make sure your laptop is fully charged before you come to class as the number of outlets in the classroom will not be sufficient to accommodate everyone.

More information on the **UC Davis Financial Aid and Scholarships Computer Loan Program** laptops can be found [here](UC%20Davis%20Financial%20Aid%20and%20Scholarships%20Computer%20Loan%20Program).

The weekly discussion/lab will be the place where you will practice the content you learned during lectures. You will be required to submit a report at the end of each week, these will be 30 percent of your grade.

## Teams

You will be assigned to a team during lecture 1, this will be your team for your final project. You are encouraged to sit with your teammates in lecture and you will also work with them in the lab sessions. All team members are expected to contribute equally to the final project. Failure to adequately contribute to an assignment will result in a penalty to your mark relative to the team's overall mark.

You are expected to make use of the provided GitHub repository for your final project as their central collaborative platform. Commits to this repository will be used as a metric (one of several) of each team member's relative contribution for the final project.

## Assessment

Assessment for the course is comprised of four components: application exercises, labs, final project, and final exam.

### Application exercises

Parts of some lectures will be dedicated to working on Application Exercises (AEs). These exercises which give you an opportunity to practice apply the statistical concepts and code introduced in the readings and lectures. These AEs are due by the end of the lecture period.

Because these AEs are for practice, they will be graded based on completion, i.e., a good-faith effort has been made in attempting all parts. Successful on-time completion of at least 80% of AEs will result in full credit for AEs in the final course grade.

You will submit these on canvas.

### Labs

In labs, you will apply the concepts discussed in lecture to various data analysis scenarios, with a focus on the computation. Most lab assignments will be completed in individually. Lab assignments will be completed using Quarto and submitted for grading on canvas by the end of the day of the week.

You will submit your lab using a quiz format, including one question where you will upload your quarto document for submission.

For example, Lab Assignment #1 on Thursday June 25 will be due Sunday June 28 at 12:59 PM.

### Final Project

The purpose of the final project is to apply what you've learned throughout the summer to analyze an interesting, data-driven research question. The project will be completed with your lab teams, and each team will present their work during the final lecture period. More information about the project will be provided during the first week of the summer session.

## Grading

The final course grade will be calculated as follows:

| Category                             | Percentage   |
|--------------------------------------|--------------|
| Application Exercises (Particpation) | 15%          |
| Labs                                 | 35% (7% x 5) |
| Final Project                        | 50%          |

The final letter grade will be determined based on the following thresholds:

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

## Course policies

### Academic integrity

Cheating and plagiarism will be evaluated and disciplined according to University policy. For information on academic integrity, please read: <http://cai.ucdavis.edu/aip.html.> You are responsible for understanding and following all aspects of University policy on academic integrity; ignorance is not an excuse. All suspected violations will be referred to Student Judicial Affairs for evaluation. You will be notified promptly by email if a referral is made.

### Policy on sharing and reusing code

I am well aware that a huge volume of code is available on the web to solve any number of problems. Unless I explicitly tell you not to use something, the course's policy is that you may make use of any online resources (e.g. RStudio Community, StackOverflow) but you must explicitly cite where you obtained any code you directly use (or use as inspiration).

### Policy on AI

AI is not allowed for usage in this classroom. You may not use artificial intelligence tools such as ChatGPT, Gemini, Claude, Grok, etc. to complete academic work being submitted for credit in the UC Davis Department of Political Science. The Office of Student Support and Judicial Affairs (OSSJA) considers the unauthorized use of content generated by artificial intelligence (AI) to be academic misconduct and/or plagiarism (see: <https://ossja.ucdavis.edu/code-academic-conduct).>

Taking credit for any work not created by the student; work includes, but is not limited to, books, articles, experimental methodology or results, compositions, images, lectures, computer programs, internet postings, and content generated by software or artificial intelligence

### Late work policy

The due dates for assignments are there to help you keep up with the course material and to ensure the teaching team can provide feedback within a timely manner. We understand that things come up periodically that could make it difficult to submit an assignment by the deadline.

-   Labs may be submitted up to 3 days late. There will be a 5% deduction for each 24-hour period the assignment is late.

-   The late work policy for the project will be provided with the project instructions.

### Waiver for extenuating circumstances

If there are circumstances that prevent you from completing a lab or project assignment by the stated due date, you may email me before the deadline to waive the late penalty. In your email, you only need to request the waiver; you do not need to provide explanation. This waiver may only be used for once in the semester, so only use it for a truly extenuating circumstance.

### Regrade request policy

Regrade requests must be submitted within a week of when an assignment is returned. A Regrade requests will be considered if there was an error in the grade calculation or if you feel a correct answer was mistakenly marked as incorrect. Requests to dispute the number of points deducted for an incorrect response will not be considered. Note that by submitting a regrade request, the entire question will be graded which could potentially result in losing points.

*No grades will be changed after the final project presentations.*

### Attendance policy

Responsibility for class attendance rests with individual students. Since regular and punctual class attendance is expected, students must accept the consequences of failure to attend.

Participation during lectures will be 15 percent of your grade, and will be graded using the application exercises. Successful completion of 80 percent of these will result in full credit for the course.

If you are absent due to illness, religious reasons, etc. please email me directly. Please note, that work conflicts are not considered an excused absence.

### Policy on video recording course content

If you feel that you need record the lectures yourself, you must get permission from me ahead of time and these recordings should be used for personal study only, no for distribution. Unauthorized distribution is a cause for disciplinary action by the Judicial Board.

*Note:* If you've read this far in the syllabus, email me a picture of your pet if you have one or your favourite meme for extra credit!

### Copyright

My lectures and course materials, including presentations, essay questions, outlines, exams, and similar materials, are protected by U.S. copyright law and by University policy. I am the exclusive owner of the copyright in those materials I create. You may take notes and make copies of course materials for your own use. You may also share those materials with another student who is enrolled in or auditing this course. You may not reproduce, distribute or display (post/upload) lecture notes or recordings or course materials in any other way (whether or not a fee is charged) without my express prior written consent. You also may not allow others to do so. Violations will be reported to the Office of Student Support and Judicial Affairs and may be subject to student conduct proceedings under the UC Davis Code of Academic Conduct.

## Important dates

-   **June 22:** Classes begin
-   **June 28:** Project Ideas Due
-   **July 17:** Project Draft Due
-   **July 22:** Project Peer Review Due
-   **July 29:** Final Projects Due
-   **July 30:** Final Project Presentation

Click [here](https://registrar.ucdavis.edu/calendar/academic-calendar) for the full UC Davis academic calendar.

## **Credits**

This course draws on code, content, ideas, inspirations and much more from work by Juan Tellez, Chris Hare, Mine Çetinkaya-Rundel**,** Andrew Heiss, Nick C. Huntington-Klein, Kieran Healy, Scott Cunningham, Richard McElreath and others who have made their courses publicly available.
