---
title: "POL 051: The Scientific Study of Politics"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the summer session. Note that this schedule will be updated as the summer progresses, with all changes documented here.

+------------------------------------+----------------------+--------------------------------------+
| Instructor:                        | Lecture:             | Discussion/Lab:                      |
+------------------------------------+----------------------+--------------------------------------+
| | Ms. Haley Daarstad               | | Monday - Wednesday | | Thursday                           |
| | 569 Kerr Hall                    | | 12:10 pm - 1:50 pm | | 12:10 pm - 1:50 pm                 |
| | hbdaarstad\@ucdavis.edu          | | Hoagland Hall 168  | | Teaching and Learning Complex 2212 |
| | Office Hours: Tue 2:00 - 4:00 PM |                      |                                      |
+------------------------------------+----------------------+--------------------------------------+

| Week | Date | Topic | Prepare | Slides | AE | Lab | Exam | Project |
|:---:|:---:|---|:---:|:---:|:---:|:---:|:---:|:---:|
| [1](/weeks/week-1.html) | Mon, June 22 | Lecture 1 - Meet + greet, Welcome to POL 051 | [📖](/weeks/week-1.html#prepare){aria-label="Week 1 summary"} | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 1 slides"} | [📋](/ae/files/ae-1-rbasics.qmd){download="ae-1-rbasics.qmd"} | | | Teams created + list of project ideas 📂 |
| | Tue, June 23 | Lecture 2 - Data Visualization I & II | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 2 slides"} | | | | |
| | Wed, June 24 | Lecture 3 - Data Wrangling I | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 3 slides"} | | | | |
| | Thu, June 25 | Lab 1 | | [🖥️](not-available-lec.html "Lab slides"){aria-label="Lab 1 slides"} | | [💻](not-available.html){aria-label="Lab 1 instructions"} | | Chosen Topic is Due June 28 📂 |
| [2](/weeks/week-2.html) | Mon, June 29 | Lecture 4 - Data Wrangling II | [📖](not-available-lec.html){aria-label="Week 2 summary"} | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 4 slides"} | | | | |
| | Tue, June 30 | Lecture 5 - Relationships I | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 5 slides"} | | | | |
| | Wed, July 1 | Lecture 6 - Relationships II | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 6 slides"} | | | | |
| | Thu, July 2 | Lab 2 | | | | [💻](not-available.html){aria-label="Lab 2 instructions"} | | |
| [3](/weeks/week-3.html) | Mon, July 6 | Lecture 7 - Modeling I | [📖](not-available-lec.html){aria-label="Week 3 summary"} | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 7 slides"} | | | | |
| | Tue, July 7 | Lecture 8 - Modeling II | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 8 slides"} | | | | |
| | Wed, July 8 | Lecture 9 - Causality I | | | | | | |
| | Thu, July 9 | Lab 3 | | [🖥️](not-available-lec.html "Lab slides"){aria-label="Lab 3 slides"} | | [💻](not-available.html "Lab instructions"){aria-label="Lab 3 instructions"} | | |
| [4](/weeks/week-4.html) | Mon, July 13 | Lecture 10 - Causality II | [📖](not-available-lec.html){aria-label="Week 4 summary"} | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 10 slides"} | | | | |
| | Tue, July 14 | Lecture 11 - DAGs | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 11 slides"} | | | | |
| | Wed, July 15 | Lecture 12 - Uncertainty | | | | | | |
| | Thu, July 16 | Lab 4 | | [🖥️](not-available-lec.html "Lab slides"){aria-label="Lab 4 slides"} | | [💻](not-available.html "Lab instructions"){aria-label="Lab 4 instructions"} | | Project Draft Due Fri. July 17 📂 |
| [5](/weeks/week-5.html) | Mon, July 20 | Lecture 13 - Hypothesis Testing I | [📖](not-available-lec.html){aria-label="Week 5 summary"} | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 13 slides"} | | | | |
| | Tue, July 21 | Lecture 14 - Hypothesis Testing II | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 14 slides"} | | | | |
| | Wed, July 22 | Lecture 15 - Prediction | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 15 slides"} | | | | Peer Review is Due 📂 |
| | Thu, July 23 | Lab 5 | | | | [💻](not-available.html "Lab instructions"){aria-label="Lab 5 instructions"} | | |
| [6](/weeks/week-6.html) | Mon, July 27 | Lecture 17 - Experiments | [📖](not-available-lec.html){aria-label="Week 6 summary"} | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 17 slides"} | | | | |
| | Tue, July 28 | Lecture 18 - Natural Experiments I | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 18 slides"} | | | | |
| | Wed, July 29 | Lecture 19 - Natural Experiments II | | [🖥️](not-available-lec.html "Lecture slides"){aria-label="Lecture 19 slides"} | | | | Final Project Due |
| | Thu, July 30 | Final Project Presentation | | | | | | Final Project Presentation 📂 |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

+------+------+-------+---------+--------+----+------------------------------------------------------------------------------------------------------------+---------+
|      |      |       | Prepare | Slides | AE | Labs                                                                                                       | Project |
+======+======+=======+:=======:+:======:+:==:+:==========================================================================================================:+:=======:+
| Week | Date | Topic | 📖      | 🖥️     | 📋 | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | 📂      |
+------+------+-------+---------+--------+----+------------------------------------------------------------------------------------------------------------+---------+
