---
title: "Project Data Options"
---

```{r include = F}
library(tidyverse)
library(knitr)
library(broom)
```

## List of Data Options for the Project

### Pew Research Data

#### US Trends Data

This data was collected by the Pew Research center in August and asks US respondents questions related to political identity, tipping, and sports.

-   Download [CSV](data/01_data/pewresearch_ustrends.csv){download="pewresearch_ustrends.csv"}

-   Download [Codebook](data/02_codebooks/pewresearch_ustrends_codebook.docx){download="pewresearch_ustrends_codebook.docx"}

#### Global Atttidues Data

This data was collected by the Pew Research center in and includes respondents from 23 countries that asks questions related to politics, AI, and climate.

-   Download [CSV](data/01_data/pewresearch_globalattitudes.csv){download="pewresearch_globalattitudes.csv"}

-   Download [Codebook](data/02_codebooks/pewresearch_globalattitudes_codebook.docx){download="pewresearch_globalattitudes_codebook.docx"}

### LAPOP Data

The LAPOP data is from the 2004 - 2023 LAPOP waves.

#### Politics and Exposure to Violence

This data includes questions on demographics, political engagement, government trust, violence, and gender specific questions for the following countries in Latin America: Mexico, Nicaragua, Haiti, Peru, Chile, Brazil, and Colombia, and Paraguay.

#### Mexico

-   Download [Mexico CSV](data/01_data/lapop_mexico.csv){download="lapop_mexico.csv"}

-   Download [Mexico codebook](data/02_codebooks/LAPOP_Codebook_Mexico.docx){download="LAPOP_Mexico.docx"}

#### Nicaragua

-   Download [Nicaragua CSV](data/01_data/lapop_nicaragua.csv){download="lapop_nicaragua.csv"}

-   Download [Nicaragua codebook](data/02_codebooks/LAPOP_Codebook_Nicaragua.docx){download="LAPOP_Nicaragua.docx"}

#### Haiti

-   Download [Haiti CSV](data/01_data/lapop_haiti.csv){download="lapop_haiti.csv"}

-   Download [Haiti codebook](data/02_codebooks/LAPOP_Codebook_Haiti.docx){download="LAPOP_Haiti.docx"}

#### Chile

-   Download [Chile CSV](data/01_data/lapop_chile.csv){download="lapop_chile.csv"}

-   Download [Chile codebook](data/02_codebooks/LAPOP_Codebook_Chile.docx){download="LAPOP_Chile.docx"}

#### Brazil

-   Download [Brazil CSV](data/01_data/lapop_brazil.csv){download="lapop_brazil.csv"}

-   Download [Brazil codebook](data/02_codebooks/LAPOP_Codebook_Brazil.docx){download="LAPOP_Brazil.docx"}

#### Colombia

-   Download [Colombia CSV](data/01_data/lapop_colombia.csv){download="lapop_colombia.csv"}

-   Download [Colombia codebook](data/02_codebooks/LAPOP_Codebook_Colombia.docx){download="LAPOP_Colombia.docx"}

#### Paraguay

-   Download [Paraguay CSV](data/01_data/lapop_paraguay.csv){download="lapop_paraguay.csv"}

-   Download [Paraguay codebook](data/02_codebooks/LAPOP_Codebook_Paraguay.docx){download="LAPOP_Paraguay.docx"}

### US Election Data

#### 2008 Election

This data includes questions on demographics, ....

-   Download CSV

-   Download Codebook

#### 2020 Election

This data includes questions on demographics, ....

-   Download CSV

-   Download Codebook

#### 2024 Election

This data includes questions on demographics, ....

-   Download CSV

-   Download Codebook

### US Migration Data

-   Download [CSV](data/01_data/immigration.csv){download="immigration.csv"}

-   Download [Codebook](data/02_codebooks/immigration_codebook.docx){download="immigration_codebook.docx"}
