{
  "hash": "627bc5e387e0f3ce733648aa4101d83b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear Regression Modeling\"\n---\n\n\n\n\n### OLS\n\n**OLS (Ordinary Least Squares)** helps us fit a line to the data to best explain how one variable (X) affects another variable (Y)\n\nLinear regression is the most commonly used approach for modeling\n\n-   It involves a numerical outcome variable, y, and explanatory variables, x, that are either numerical or categorical.\n\n-   We assume the relationship between X and Y is linear (a line) Useful for prediction and explanation.\n\n$$\nY_i = \\alpha + \\beta X + u_i\n$$\n\nWe use sample data to make inferences about the population of interest, therefore our regression formula is:\n\n$$\n\\hat Y_i = \\hat\\alpha + \\hat\\beta X + \\hat u_i\n$$\n\nThe hat (\\^) are indicators of a sample data not the true population estimate.\n\n-   Y: dependent, outcome variable\n\n-   X: independent, explanatory variable\n\n-   𝜶  and β: are the parameter estimates\n\n    -   𝜶 : The predicted value of Y when X= 0 (intercept)\n\n    -   β: how much Y changes for a one-unit increase in X (slope)\n\nWe use linear regressions to estimate how x changes are y! Therefore, how we interpret the estimate, β, is determined by whether our x value is a categorical or continuous variable.\n\nHere is the formula to Interpreting Regressions:\n\n-   Continuous Variable -\\> Look at the slope!\n\n    -   When X increases 1 unit, Y increases by 𝛽\n\n    -   Usually, you can ignore the intercept The intercept is the average value of Y when X =0.\n\n-   Dummy/Categorical Variable -\\> Compare it with the baseline category (aka intercept)\n\n    -   When X is in the given category, average Y value is higher by 𝛽 compared to the average Y value for baseline X.\n\n    -   The intercept is the average Y value for the baseline category.\n\n| Type | Approach | Interpetation |\n|------------------------|------------------------|------------------------|\n| Continious | A one unit increase in X, SLOPE unit change in Y. | For every \\_\\_\\_ (replace with unit value) increase in \\_\\_\\_ (replace with X value) results in \\_\\_\\_ (replace with estimate/slope) unit change in \\_\\_\\_ (replace with Y, or outcome value) |\n| Categorical | The category is SLOPE unites higher/lower than the intercept. | The \\_\\_\\_ (replace with categorical value) is \\_\\_\\_ (replace with estimate/slope) higher/lower than \\_\\_\\_ (replace with baseline/intercept) |\n\nThe function to calculate this in R is: `lm()`\n\nExample:\n\nI will be using the same randomly generated data as the correlations examples.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(123)\n\nage <- sample(18:100, 100, replace = TRUE)\ngender <- sample(c(1, 0), 100, replace = TRUE)  # 1 = Female, 0 = Male\nkids <- sample(0:5, 100, replace = TRUE)\n\n# Now build the data.frame with dependent vars defined inline\ndata <- data.frame(\n  age = age,\n  gender = gender,\n  height = rnorm(100, mean = 5.5, sd = 0.75) + gender * -0.25,\n  kids = kids,\n  income = rnorm(100, mean = 45000, sd = 10000) + age * 1000 + gender * (-2000) + kids * (-3000),\n  years_edu = sample(10:23, 100, replace = TRUE) + age * 1 + gender * 2\n)\n\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  age gender   height kids    income years_edu\n1  48      1 4.578477    1  82225.32        63\n2  96      1 4.266899    2 153024.83       121\n3  68      0 6.997910    0 113667.01        89\n4  31      1 5.700532    0  92668.52        49\n5  84      0 4.561546    4 103490.97        97\n6  59      0 5.041626    4  92209.84        81\n```\n\n\n:::\n:::\n\n\n\n\nFirst, we will doing a simple linear regression with only one X value. Y is our outcome variable and X is our explantory variable. it will look like the following:\n\n`lm(y ~ x, data)`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# categorical interpetation\nmodel1 <- lm(height ~ gender, data)\n\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = height ~ gender, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.40414 -0.47142 -0.07808  0.44609  1.70882 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  5.51099    0.09734  56.616   <2e-16 ***\ngender      -0.17425    0.14352  -1.214    0.228    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7153 on 98 degrees of freedom\nMultiple R-squared:  0.01482,\tAdjusted R-squared:  0.004766 \nF-statistic: 1.474 on 1 and 98 DF,  p-value: 0.2276\n```\n\n\n:::\n:::\n\n\n\n\nOur estimate, how much x changes y, is **-0.17**, and our baseline, Male's height, is **5.51** feet, which we can interpret as the following:\n\nMen are on average **5.51** feet high, and women are on average **0.17 feet shorter** than Men.\n\nHowever, we can not say according to our data that gender is correlated with height, since according to our P-value column, our **p-value is 0.228**, which is more than 0.05.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# continious interpetation\nmodel2 <- lm(income ~ age, data)\n\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = income ~ age, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-28480.3  -7731.4    436.7   7645.8  30540.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 34967.79    3405.90   10.27   <2e-16 ***\nage          1045.02      53.15   19.66   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12550 on 98 degrees of freedom\nMultiple R-squared:  0.7977,\tAdjusted R-squared:  0.7957 \nF-statistic: 386.5 on 1 and 98 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nWe want to look at the column with the estimate first, this tells us our intercept and estimate.\n\nOur estimate, how much x changes y, is **1045.02**, and our intercept is **34,967.79**, which we can interpret as the following:\n\nAt 18 years old (which is the lowest age we have), income is **34,967.79**, and for every year older, an individuals income increases by **1045.02** dollars.\n\nIn additon, we can say according to our data that age is correlated with income, since according to our P-value column, our **p-value is \\<2e-16**, which is less than 0.05.\n\nIn addition you can see \\*\\*\\* after our p-value, this tells us the level of significance, the more stars the stronger the significance.\n\n### Multivariate Linear Regressions\n\nNow, we have just been looking at one explanatory variable, however, you may want to look are more than one and also consider that there maybe outside influence that you need to control for.\n\nFurthermore, you may want to add more x variables. To do this, you can do the following:\n\n`lm(y ~ x1 + x2 + x3 + ... + xn , data)`\n\nNow, lets look at an example, but first, lets make some random generated data real quick!\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What if we have a confounding variable?\n\n# This will be our confounding variable\nweekly_exercise <- rnorm(100,5,2)\n\n# lets make our new dataframe\ndf_confound <- tibble(income_scale = (rnorm(100,30000,10000) + 10000*weekly_exercise)/1000,\n                      age = rnorm(100,35,10),\n                      # this is another function that creats a binary variable based on probability \n                      female = rbinom(100,1,.5),\n                      heart_health = 60 + 10*weekly_exercise - 1*age + 8*female + rnorm(100,0,10))\n\n# regression model\nmodel3 <- lm(heart_health ~ income_scale + age + female, df_confound)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = heart_health ~ income_scale + age + female, data = df_confound)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-25.394  -8.562  -0.513   8.813  36.603 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  51.69599    6.64099   7.784 8.10e-12 ***\nincome_scale  0.72808    0.05986  12.162  < 2e-16 ***\nage          -0.91499    0.12930  -7.077 2.41e-10 ***\nfemale        7.54097    2.80779   2.686  0.00853 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 13.21 on 96 degrees of freedom\nMultiple R-squared:   0.68,\tAdjusted R-squared:   0.67 \nF-statistic: 67.99 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# visual\ndf_confound |>\n  ggplot(aes(x = income_scale, y = heart_health)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](models_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\nOkay! There is something wrong with this model yes? We know income scale doesn't actually impact heart health, rather this is done through weekly exercise! To take this into account we can do the following:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.fix <- lm(heart_health ~ weekly_exercise + income_scale + age + female, df_confound)\nsummary(model.fix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = heart_health ~ weekly_exercise + income_scale + \n    age + female, data = df_confound)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-24.8789  -7.5206  -0.6986   7.2529  25.7713 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     61.75064    5.56561  11.095  < 2e-16 ***\nweekly_exercise  9.62967    1.34813   7.143 1.84e-10 ***\nincome_scale     0.01537    0.11096   0.139     0.89    \nage             -1.01886    0.10584  -9.626 1.04e-15 ***\nfemale           9.36947    2.29096   4.090 9.04e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.71 on 95 degrees of freedom\nMultiple R-squared:  0.7918,\tAdjusted R-squared:  0.783 \nF-statistic: 90.32 on 4 and 95 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_confound |>\n  ggplot(aes(x=weekly_exercise,y = heart_health)) + \n  geom_point()+\n  # lets add a line based on using a linear regression\n  geom_smooth(method =\"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](models_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\nNow, income is no longer correlated!\n\n## Class Examples\n\n### Who Trades? 🚢\n\nFit a model that estimates how much a country exports, using a treatment variable of your choosing. Interpret the model output.\n\n1.  Use the dataset `trade` in the package `juanr`\n\n2.  Identify your y (outcome) and x (explanatory) variables\n\n3.  Use the `lm()` function to fit a model\n\n4.  Use `tidy()` to show the outcomes of the model\n\nTo use `tidy()` use the `broom` package\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(juanr)\nlibrary(tidyverse)\nlibrary(broom)\n\n?trade\n\ntrade_ols <- lm(exports ~ sum_igos, data = trade)\n\ntidy(trade_ols)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)  -64655.    2580.      -25.1 2.55e-134\n2 sum_igos       1868.      47.7      39.1 6.75e-311\n```\n\n\n:::\n:::\n\n\n\n\n### 👨‍👧‍👦 Kids 👨‍👧‍👦\n\nUsing the `gss_sm dataset`:\n\nDo happier people tend to have more or fewer kids than less happy people? Regress `childs` (outcome) against `happy` (treatment). Interpret the output.\n\nHow does religion affect family size? Regress the number of siblings `sibs` (outcome) against respondent religion `relig`. Based on the output: which religion has the largest families, on average?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(socviz)\n\n?gss_sm\n\ngss_sm |>\n  distinct(happy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 1\n  happy        \n  <fct>        \n1 Pretty Happy \n2 Very Happy   \n3 <NA>         \n4 Not Too Happy\n```\n\n\n:::\n\n```{.r .cell-code}\nlm(childs ~ happy, data = gss_sm) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term               estimate std.error statistic   p.value\n  <chr>                 <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)           1.91     0.0586     32.6  1.13e-198\n2 happyPretty Happy    -0.145    0.0719     -2.02 4.32e-  2\n3 happyNot Too Happy    0.105    0.0980      1.07 2.86e-  1\n```\n\n\n:::\n\n```{.r .cell-code}\nlm(sibs ~ relig, data = gss_sm) |>\n  tidy() |>\n  arrange(desc(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 5\n   term                          estimate std.error statistic   p.value\n   <chr>                            <dbl>     <dbl>     <dbl>     <dbl>\n 1 (Intercept)                   3.77        0.0861  43.8     8.48e-321\n 2 religMoslem/Islam             1.86        0.736    2.53    1.15e-  2\n 3 religNative American          0.478       1.59     0.300   7.64e-  1\n 4 religCatholic                 0.452       0.152    2.97    2.96e-  3\n 5 religOther                    0.000631    0.488    0.00129 9.99e-  1\n 6 religOther Eastern           -0.0221      1.59    -0.0139  9.89e-  1\n 7 religChristian               -0.347       0.511   -0.680   4.97e-  1\n 8 religNone                    -0.484       0.154   -3.14    1.72e-  3\n 9 religOrthodox-Christian      -0.486       1.21    -0.403   6.87e-  1\n10 religInter-Nondenominational -0.915       1.21    -0.758   4.48e-  1\n11 religBuddhism                -0.963       0.700   -1.37    1.69e-  1\n12 religJewish                  -1.93        0.454   -4.25    2.23e-  5\n13 religHinduism                -2.00        0.887   -2.26    2.41e-  2\n```\n\n\n:::\n:::\n",
    "supporting": [
      "models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}